
server:
  port: 8083
  servlet:
    context-path: /pagamento-backend
  
spring:
  application:
    name: pagamento
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/u2d-pagamento?allowPublicKeyRetrieval=true&sslMode=DISABLED&createDatabaseIfNotExiste=true
    username: root
    password: 415782
  flyway:
    baseline-on-migrate: true
  jmx:
    enabled: false